name: calm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.7.4.post0
      - annotated-types==0.6.0
      - async-timeout==3.0.1
      - attrs==23.2.0
      - base58==2.1.1
      - bitsandbytes-cuda113==0.26.0.post2
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==4.0.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - configargparse==1.7
      - configparser==7.0.0
      - cryptography==42.0.5
      - datasets==1.17.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - filelock==3.13.4
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.62.1
      - grpcio-tools==1.62.1
      - huggingface-hub==0.22.2
      - idna==2.10
      - joblib==1.4.0
      - msgpack==1.0.8
      - multiaddr==0.0.9
      - multidict==6.0.5
      - multiprocess==0.70.16
      - netaddr==1.2.1
      - nltk==3.6.7
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.2
      - pathtools==0.1.2
      - pillow==10.3.0
      - prefetch-generator==1.0.3
      - promise==2.3
      - psutil==5.9.8
      - pyarrow==15.0.2
      - pycparser==2.22
      - pydantic==1.10.14
      - pymultihash==0.8.2
      - python-dateutil==2.9.0.post0
      - pytorch-ranger==0.1.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.25.1
      - sacremoses==0.1.1
      - scipy==1.13.0
      - sentencepiece==0.1.96
      - sentry-sdk==1.45.0
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - subprocess32==3.5.4
      - termcolor==1.1.0
      - tokenizers==0.10.3
      - torch-optimizer==0.1.0
      - tqdm==4.66.2
      - transformers==4.12.2
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==1.26.18
      - uvloop==0.19.0
      - varint==1.0.2
      - wandb==0.12.1
      - xxhash==3.4.1
      - yarl==1.9.4
